# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMWRC3e_ved6rEbLsxxer9nWjJzCYLDH
"""
# Recuperado de:
# https://jckantor.github.io/ND-Pyomo-Cookbook/04.03-Job-Shop-Scheduling.html

import pandas as pd
#%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl

results = [{'Duration': 45,
  'Finish': 87.0,
  'Job': 'Paper_1',
  'Machine': 'Blue',
  'Start': 42.0},
 {'Duration': 10,
  'Finish': 97.0,
  'Job': 'Paper_1',
  'Machine': 'Yellow',
  'Start': 87.0},
 {'Duration': 20,
  'Finish': 30.0,
  'Job': 'Paper_2',
  'Machine': 'Blue',
  'Start': 10.0},
 {'Duration': 10,
  'Finish': 10.0,
  'Job': 'Paper_2',
  'Machine': 'Green',
  'Start': 0.0},
 {'Duration': 34,
  'Finish': 64.0,
  'Job': 'Paper_2',
  'Machine': 'Yellow',
  'Start': 30.0},
 {'Duration': 12,
  'Finish': 42.0,
  'Job': 'Paper_3',
  'Machine': 'Blue',
  'Start': 30.0},
 {'Duration': 17,
  'Finish': 59.0,
  'Job': 'Paper_3',
  'Machine': 'Green',
  'Start': 42.0},
 {'Duration': 28,
  'Finish': 28.0,
  'Job': 'Paper_3',
  'Machine': 'Yellow',
  'Start': 0.0}]

def visualize(results):
    
    schedule = pd.DataFrame(results)
    JOBS = sorted(list(schedule['Job'].unique()))
    MACHINES = sorted(list(schedule['Machine'].unique()))
    makespan = schedule['Finish'].max()
    
    bar_style = {'alpha':1.0, 'lw':25, 'solid_capstyle':'butt'}
    text_style = {'color':'white', 'weight':'bold', 'ha':'center', 'va':'center'}
    colors = mpl.cm.Dark2.colors

    schedule.sort_values(by=['Job', 'Start'])
    schedule.set_index(['Job', 'Machine'], inplace=True)

    fig, ax = plt.subplots(2,1, figsize=(12, 5+(len(JOBS)+len(MACHINES))/4))

    for jdx, j in enumerate(JOBS, 1):
        for mdx, m in enumerate(MACHINES, 1):
            if (j,m) in schedule.index:
                xs = schedule.loc[(j,m), 'Start']
                xf = schedule.loc[(j,m), 'Finish']
                ax[0].plot([xs, xf], [jdx]*2, c=colors[mdx%7], **bar_style)
                ax[0].text((xs + xf)/2, jdx, m, **text_style)
                ax[1].plot([xs, xf], [mdx]*2, c=colors[jdx%7], **bar_style)
                ax[1].text((xs + xf)/2, mdx, j, **text_style)
                
    ax[0].set_title('Job Schedule')
    ax[0].set_ylabel('Job')
    ax[1].set_title('Machine Schedule')
    ax[1].set_ylabel('Machine')
    
    for idx, s in enumerate([JOBS, MACHINES]):
        ax[idx].set_ylim(0.5, len(s) + 0.5)
        ax[idx].set_yticks(range(1, 1 + len(s)))
        ax[idx].set_yticklabels(s)
        ax[idx].text(makespan, ax[idx].get_ylim()[0]-0.2, "{0:0.1f}".format(makespan), ha='center', va='top')
        ax[idx].plot([makespan]*2, ax[idx].get_ylim(), 'r--')
        ax[idx].set_xlabel('Time')
        ax[idx].grid(True)
        
    fig.tight_layout()

visualize(results)